export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCTS_FILTER ='FETCH_PRODUCTS_WITH_FILTER';
export const FETCH_Cart_PRODUCTS_REQUEST = 'FETCH_CART_PRODUCTS_REQUEST';
export const FETCH_Cart_PRODUCTS_SUCCESS = 'FETCH_CART_PRODUCTS_REQUEST';
export const FETCH_Cart_PRODUCTS_FAILURE = 'FETCH_CART_PRODUCTS_REQUEST';